# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- __main__

variables:
  - name: system.debug
    value: true
resources:
  webhooks:
    - webhook: GitHubIntegration
      connection: GitHubWebhook

pool:
  vmImage: ubuntu-latest

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      get-childitem env:
      #start-sleep -Seconds 240



- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  ${{ if false }}: 
    displayName : 'Run a multi-line script'
  ${{ else }}:
    displayName :   'some else'
