name : Get PR Contents

on :
  pull_request : 
    branches : 
      - main
      - feature/*
    paths-ignore: 
      - '.github/**'
          
  workflow_dispatch : 

jobs : 
  call_external :
    uses : T4dP0les/sharedWorflows/.github/workflows/extractPRContents.yaml@main
    secrets :
      github_token : ${{ secrets.GITHUB_TOKEN }}
