name : Get PR Contents from Shared

on :
  pull_request : 
    branches : 
      - main
      - feature/*
    paths-ignore: 
      - '.github/**'
          
  workflow_dispatch : 

jobs : 
  call_external :
    #permissions:
    #  actions: write
    permissions: write-all
    uses : T4dP0les/sharedWorkflows/.github/workflows/extractPRContents.yaml@main
    secrets :
      #
      caller_github_token : ${{ secrets.GITHUB_TOKEN }}
      #caller_github_token : ${{ secrets.GITPOSTAUTH }}
