name: Runners Contents

on:
  workflow_dispatch :
  
jobs:

  build-windows:
    runs-on: windows-latest  

    env:
      Solution_Name: your-solution-name                       

    steps:
    - name : dump folder structure
      shell : cmd
      run : |
        mkdir D:\artefact
        dir /s D:\ > D:\artefact\allFiles.txt
        REM dir /s C:\ >> D:\artefact\allFiles.txt
        
    # Upload
    - name: folder struct 
      uses: actions/upload-artifact@main
      with:
        name: AllFilesWindows.txt
        path: D:\Artefact\allFiles.txt


  build-linux:
    runs-on: ubuntu-latest  

    env:
      Solution_Name: your-solution-name                       

    steps:
    - name : dump folder structure
      shell : bash
      run : |
        printenv | sort
        ls -al / 
        mkdir $HOME/artefact
        ls -al / > $HOME/artefact/allFiles.txt
        #find $HOME -name "*.*"

    - name: zip 
      shell : pwsh
      run : |
        #GITHUB_WORKSPACE=/home/runner/work/consoleApp/consoleApp
        Compress-Archive -Path $env:GITHUB_WORKSPACE/* -DestinationPath $env:HOME/artefact/Payload.zip
    # Upload
    - name: folder struct 
      uses: actions/upload-artifact@main
      with:
        name: AllFilesLinux.txt
        path: /home/runner/artefact/allFiles.txt
