name: Runners Contents

on:
  workflow_dispatch :
  
jobs:

  build-windows:
    runs-on: windows-latest  

    env:
      Solution_Name: your-solution-name                       

    steps:
    - name : checkout
      uses : actions/checkout@main
      with :
        fetch-depth : 1
    - name : dump env vars 
      shell : pwsh
      run : |
        get-childitem env:

    - name : dump folder structure
      shell : cmd
      run : |
        SET
        mkdir D:\artefact
        dir /s D:\ > D:\artefact\allFiles.txt
        REM dir /s C:\ >> D:\artefact\allFiles.txt
        
    # Upload
    - name: folder struct 
      uses: actions/upload-artifact@main
      with:
        name: AllFilesWindows.txt
        path: D:\Artefact\allFiles.txt


  build-linux:
    runs-on: ubuntu-latest  

    env:
      Solution_Name: your-solution-name                       

    steps:
    - name : checkout
      uses : actions/checkout@main
      with :
        fetch-depth : 1
        
    - name : dump folder structure
      shell : bash
      run : |
        printenv | sort
        ls -al / 
        mkdir $HOME/artefact
        ls -al / > $HOME/artefact/allFiles.txt
        #find $HOME -name "*.*"

    - name: zip 
      shell : pwsh
      run : |
        #GITHUB_WORKSPACE=/home/runner/work/consoleApp/consoleApp
        #Compress-Archive -Path $env:GITHUB_WORKSPACE/* -DestinationPath $env:HOME/artefact/Payload.zip
        write-host "HOME : $env:HOME"
        write-host "GITHUB_WORKSPACE : $env:GITHUB_WORKSPACE"
        #Compress-Archive -Path /home/runner/work/consoleApp/* -DestinationPath /home/runner/artefact/Payload.zip
        Get-childitem -path /home/runner/work/consoleApp -recurse
        Get-childitem -path /home/runner/work/consoleApp -recurse | Compress-Archive -DestinationPath /home/runner/artefact/Payload.zip
        get-childitem -path /home/runner/artefact
    # Upload
    - name: Upload allFiles 
      uses: actions/upload-artifact@main
      with:
        name: AllFilesLinux.txt
        path: /home/runner/artefact/allFiles.txt

    - name: Upload struct 
      uses: actions/upload-artifact@main
      with:
        name: Payload.zip
        path: /home/runner/artefact/Payload.zip
