name: Runners Contents

on:
  workflow_dispatch :
  
jobs:

  build-windows:
    runs-on: windows-latest  

    env:
      Solution_Name: your-solution-name                       

    steps:
    - name : dump folder structure
      shell : cmd
      run : |
        mkdir D:\artefact
        dir /s D:\ > D:\artefact\allFiles.txt
        REM dir /s C:\ >> D:\artefact\allFiles.txt
        
    # Upload
    - name: folder struct 
      uses: actions/upload-artifact@main
      with:
        name: AllFilesWindows.txt
        path: D:\Artefact


  build-linux:
    runs-on: ubuntu-latest  

    env:
      Solution_Name: your-solution-name                       

    steps:
    - name : dump folder structure
      shell : bash
      run : |
        printenv
        mkdir $HOME/artefact
        ls / > $HOME/artefact/allFiles.txt
        
    # Upload
    - name: folder struct 
      uses: actions/upload-artifact@main
      with:
        name: AllFilesLinux.txt
        path: /artefact
